---
# tasks file for flatcar-linux

- name: Use localhost to provision Azure virtual machines
  include_tasks: provision_azure_coreos_virtual_machines.yml
  delegate_to: localhost

- name: Download and Install Azure dynamic inventory script
  include_tasks: azure_dynamic_inventory_script.yml
  delegate_to: localhost

- include_tasks: bootstrap_pypy_for_ansible.yml
  when: ansible_distribution == "Container Linux by CoreOS"

- include_tasks: coreos_upgrade_to_flatcar_linux.yml
  when: ansible_distribution == "Container Linux by CoreOS"

#when: ansible_distribution ==  "Flatcar Linux by Kinvolk", 
